# Generated by Django 5.0.6 on 2024-07-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipomoneda'),
            preserve_default=False,
        ),
    ]
