# Generated by Django 5.0.6 on 2024-07-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_tipomoneda_propiedad_tipo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numero_departamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
