# Generated by Django 5.0.6 on 2024-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_propiedad_numero_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='image_url',
            field=models.URLField(default='ingrese_una_url_para_la_imagen', max_length=255),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
